const fs = require('fs').promises;
const path = require('path');

/**
 * Merge discovered components with existing config.json
 *
 * Preserves manual overrides (_autoGenerated: false)
 * Updates auto-generated entries
 * Adds new discoveries
 *
 * @param {string} configPath - Path to config.json
 * @param {Object} discoveredData - Discovered components by project
 * @param {Object} mmdsComponents - Available MMDS components
 * @returns {Promise<Object>} - Merged config
 */
async function mergeConfig(configPath, discoveredData, mmdsComponents) {
  // Load existing config
  let existingConfig = {};
  try {
    const content = await fs.readFile(configPath, 'utf8');
    existingConfig = JSON.parse(content);
  } catch (err) {
    console.log('No existing config found, creating new one');
  }

  // Merge each project
  const mergedConfig = {
    projects: {},
  };

  for (const [projectName, projectData] of Object.entries(discoveredData)) {
    const existing = existingConfig.projects?.[projectName] || {};
    const merged = mergeProject(existing, projectData, mmdsComponents, projectName);
    mergedConfig.projects[projectName] = merged;
  }

  return mergedConfig;
}

/**
 * Merge a single project's configuration
 *
 * @param {Object} existing - Existing project config
 * @param {Object} discovered - Discovered project data
 * @param {Object} mmdsComponents - MMDS components
 * @param {string} projectName - 'extension' or 'mobile'
 * @returns {Object} - Merged project config
 */
function mergeProject(existing, discovered, mmdsComponents, projectName) {
  const merged = {
    ...existing,
    deprecatedComponents: {},
    currentComponents: discovered.currentComponents || existing.currentComponents || [],
    currentPackages: discovered.currentPackages || existing.currentPackages || [],
  };

  // Merge deprecated components
  const existingDeprecated = existing.deprecatedComponents || {};

  for (const [componentName, componentData] of Object.entries(discovered.deprecatedComponents)) {
    const existingComponent = existingDeprecated[componentName];

    // If component exists and is manually overridden, preserve it
    if (existingComponent && existingComponent._autoGenerated === false) {
      merged.deprecatedComponents[componentName] = existingComponent;
      continue;
    }

    // Otherwise, use the discovered data (auto-generated)
    merged.deprecatedComponents[componentName] = {
      ...componentData,
      _autoGenerated: true,
    };
  }

  // Also preserve any manual entries that weren't discovered
  for (const [componentName, componentData] of Object.entries(existingDeprecated)) {
    if (componentData._autoGenerated === false && !merged.deprecatedComponents[componentName]) {
      merged.deprecatedComponents[componentName] = componentData;
    }
  }

  return merged;
}

/**
 * Write merged config to file
 *
 * @param {string} configPath - Path to config.json
 * @param {Object} config - Config object
 */
async function writeConfig(configPath, config) {
  const content = JSON.stringify(config, null, 2);
  await fs.writeFile(configPath, content + '\n', 'utf8');
}

/**
 * Generate a summary report of changes
 *
 * @param {Object} existingConfig - Previous config
 * @param {Object} newConfig - New merged config
 * @returns {Object} - Summary report
 */
function generateReport(existingConfig, newConfig) {
  const report = {
    added: [],
    updated: [],
    removed: [],
    preserved: [],
  };

  for (const [projectName, projectConfig] of Object.entries(newConfig.projects)) {
    const existingProject = existingConfig.projects?.[projectName] || {};
    const existingDeprecated = existingProject.deprecatedComponents || {};
    const newDeprecated = projectConfig.deprecatedComponents || {};

    for (const componentName of Object.keys(newDeprecated)) {
      if (!existingDeprecated[componentName]) {
        report.added.push({ project: projectName, component: componentName });
      } else if (newDeprecated[componentName]._autoGenerated === false) {
        report.preserved.push({ project: projectName, component: componentName });
      } else {
        // Check if replacement changed
        const oldReplacement = JSON.stringify(existingDeprecated[componentName].replacement);
        const newReplacement = JSON.stringify(newDeprecated[componentName].replacement);
        if (oldReplacement !== newReplacement) {
          report.updated.push({
            project: projectName,
            component: componentName,
            old: existingDeprecated[componentName].replacement,
            new: newDeprecated[componentName].replacement,
          });
        }
      }
    }

    for (const componentName of Object.keys(existingDeprecated)) {
      if (!newDeprecated[componentName]) {
        report.removed.push({ project: projectName, component: componentName });
      }
    }
  }

  return report;
}

module.exports = {
  mergeConfig,
  writeConfig,
  generateReport,
};
