#!/usr/bin/env node

/**
 * Extract JSON data from XLSX metrics files for dashboard consumption
 *
 * Reads XLSX files generated by the metrics tool and extracts:
 * - Summary statistics
 * - Component-level details
 * - Migration status
 *
 * Generates JSON files that can be easily consumed by the web dashboard.
 *
 * Usage:
 *   node scripts/xlsx-to-json.js
 *   node scripts/xlsx-to-json.js --file metrics/mobile-metrics-2026-02-24.xlsx
 */

const ExcelJS = require('exceljs');
const fs = require('fs').promises;
const path = require('path');

const METRICS_DIR = path.join(__dirname, '..', 'metrics');

/**
 * Extract date from filename
 * e.g., "mobile-component-metrics-2026-02-24.xlsx" -> "2026-02-24"
 */
function extractDate(filename) {
  const match = filename.match(/(\d{4}-\d{2}-\d{2})/);
  return match ? match[1] : null;
}

/**
 * Extract project name from filename
 * e.g., "mobile-component-metrics-2026-02-24.xlsx" -> "mobile"
 */
function extractProject(filename) {
  if (filename.includes('mobile')) return 'mobile';
  if (filename.includes('extension')) return 'extension';
  return 'unknown';
}

/**
 * Parse XLSX file and extract component data
 */
async function parseXLSX(filePath) {
  console.log(`📖 Reading ${path.basename(filePath)}...`);

  const workbook = new ExcelJS.Workbook();
  await workbook.xlsx.readFile(filePath);

  const worksheet = workbook.getWorksheet(1); // First sheet contains the data

  if (!worksheet) {
    throw new Error('No worksheet found in XLSX file');
  }

  const components = [];
  const headers = {};

  // Read headers from first row
  const headerRow = worksheet.getRow(1);
  headerRow.eachCell((cell, colNumber) => {
    headers[colNumber] = cell.value;
  });

  // Find column indices
  const findColumn = (name) => {
    const entry = Object.entries(headers).find(([_, value]) =>
      value && value.toString().toLowerCase().includes(name.toLowerCase())
    );
    return entry ? parseInt(entry[0]) : null;
  };

  // Map columns based on actual headers
  const componentCol = findColumn('deprecated component') || findColumn('component') || 1;
  const mmdsCol = findColumn('mmds instances') || 5;
  const deprecatedCol = findColumn('deprecated instances') || 4;
  const replacementCol = findColumn('mmds component') || findColumn('replacement') || 3;
  const migratedPercentCol = findColumn('migrated %') || 6;

  // Read data rows
  worksheet.eachRow((row, rowNumber) => {
    if (rowNumber === 1) return; // Skip header

    const componentName = row.getCell(componentCol).value;
    if (!componentName) return; // Skip empty rows

    const mmdsInstances = parseInt(row.getCell(mmdsCol).value) || 0;
    const deprecatedInstances = parseInt(row.getCell(deprecatedCol).value) || 0;
    const totalInstances = mmdsInstances + deprecatedInstances;

    const component = {
      name: componentName.toString(),
      mmdsInstances,
      deprecatedInstances,
      totalInstances,
      replacement: row.getCell(replacementCol).value?.toString() || null,
      migrationPercentage: totalInstances > 0
        ? ((mmdsInstances / totalInstances) * 100).toFixed(2)
        : '0.00'
    };

    components.push(component);
  });

  // Calculate summary statistics
  const summary = {
    totalComponents: components.length,
    mmdsInstances: components.reduce((sum, c) => sum + c.mmdsInstances, 0),
    deprecatedInstances: components.reduce((sum, c) => sum + c.deprecatedInstances, 0),
    totalInstances: 0,
    migrationPercentage: '0.00',
    fullyMigrated: components.filter(c => c.deprecatedInstances === 0 && c.mmdsInstances > 0).length,
    notStarted: components.filter(c => c.mmdsInstances === 0 && c.deprecatedInstances > 0).length,
    inProgress: components.filter(c => c.mmdsInstances > 0 && c.deprecatedInstances > 0).length
  };

  summary.totalInstances = summary.mmdsInstances + summary.deprecatedInstances;
  summary.migrationPercentage = summary.totalInstances > 0
    ? ((summary.mmdsInstances / summary.totalInstances) * 100).toFixed(2)
    : '0.00';

  console.log(`  ✓ Extracted ${components.length} components`);
  console.log(`  ✓ MMDS instances: ${summary.mmdsInstances}`);
  console.log(`  ✓ Migration: ${summary.migrationPercentage}%`);

  return {
    summary,
    components: components.sort((a, b) => b.totalInstances - a.totalInstances)
  };
}

/**
 * Process a single XLSX file
 */
async function processFile(xlsxPath) {
  const filename = path.basename(xlsxPath);
  const date = extractDate(filename);
  const project = extractProject(filename);

  if (!date) {
    console.error(`  ⚠️  Could not extract date from ${filename}`);
    return null;
  }

  const data = await parseXLSX(xlsxPath);

  // Try to load the summary JSON to get mmdsComponentsAvailable and newComponents
  const summaryPath = xlsxPath.replace('.xlsx', '-summary.json');
  let mmdsComponentsAvailable = null;
  let mmdsComponentsList = null;
  let newComponents = null;
  try {
    const summaryContent = await fs.readFile(summaryPath, 'utf8');
    const summaryData = JSON.parse(summaryContent);
    mmdsComponentsAvailable = summaryData.mmdsComponentsAvailable;
    mmdsComponentsList = summaryData.mmdsComponentsList;
    newComponents = summaryData.newComponents;
  } catch (err) {
    // Summary file might not exist for older data
  }

  const output = {
    project,
    date,
    generatedAt: new Date().toISOString(),
    mmdsComponentsAvailable,
    mmdsComponentsList,
    newComponents,
    ...data
  };

  // Write JSON file
  const jsonPath = xlsxPath.replace('.xlsx', '-data.json');
  await fs.writeFile(jsonPath, JSON.stringify(output, null, 2));
  console.log(`  ✓ Written to ${path.basename(jsonPath)}\n`);

  return { project, date, file: path.basename(jsonPath) };
}

/**
 * Process all XLSX files in metrics directory
 */
async function processAllFiles() {
  const files = await fs.readdir(METRICS_DIR);
  const xlsxFiles = files
    .filter(f => f.endsWith('.xlsx') && f.includes('component-metrics'))
    .sort();

  if (xlsxFiles.length === 0) {
    console.log('⚠️  No XLSX files found in metrics/');
    return [];
  }

  console.log(`📊 Found ${xlsxFiles.length} XLSX file(s)\n`);

  const results = [];
  for (const file of xlsxFiles) {
    const filePath = path.join(METRICS_DIR, file);
    const result = await processFile(filePath);
    if (result) {
      results.push(result);
    }
  }

  return results;
}

/**
 * Main execution
 */
async function main() {
  const args = process.argv.slice(2);

  try {
    if (args.includes('--file')) {
      const fileIndex = args.indexOf('--file');
      const filePath = args[fileIndex + 1];

      if (!filePath) {
        console.error('❌ No file specified after --file');
        process.exit(1);
      }

      await processFile(filePath);
    } else {
      const results = await processAllFiles();
      console.log(`\n✅ Processed ${results.length} file(s) successfully`);
    }
  } catch (error) {
    console.error('❌ Error:', error.message);
    process.exit(1);
  }
}

main();
